config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users,
    controllers:{ omniauth_callbacks:"users/omniauth_callbacks" }

  resources :users, only: %i(show)
  namespace :admin do
    get "index"
    resources :users
    resources :categories
    resources :newspapers
    resources :leagues
    resources :seasons
    resources :players
    resources :rounds do
      resources :matches
    end
    resources :football_clubs
  end
  get "categories/new"
  mount Ckeditor::Engine => "/ckeditor"
  get "/categories", to: "home#index"
  get "/search", to:"newspapers#search"
  resources :categories
  resources :newspapers
  resources :comments
  resources :matchs
  resources :bets  
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
  NEWSPAPER_PARAMS = %i(title description image status category_id).freeze
  enum status: {normal: 0, hot: 1, most_new: 2}

  has_one_attached :image
  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy
  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true

  delegate :name, to: :category, prefix: true

  scope :ordered_by_newspaper_id, -> {order(id: :desc)}
  scope :by_status_hot, -> {where status: 1}
  scope :by_status_normal, -> {where status: 0}
  scope :get_new_by_category_ids, ->(category_ids){where category_id: category_ids}
  scope :limit_show_newspapers, -> {order(id: :asc).limit 4}
end

app/controllers/admin/newspapers_controller.rb
class Admin::NewspapersController < AdminController
  before_action :load_newspaper, except: %i(new create index)

  def index
    @newspapers = Newspaper.page(params[:page]).per Settings.paging_table
  end

  def new
    @newspaper = Newspaper.new
  end

  def create
    @newspaper = Newspaper.new newspaper_params
    if @newspaper.save
      flash[:success] = t("success")
      redirect_to admin_newspapers_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @newspaper.update newspaper_params
      flash[:success] =  t "success"
      redirect_to admin_newspapers_path
    else
      render :edit
    end
  end

  def destroy
    if @newspaper.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "error"
    end
    redirect_to admin_newspapers_path
  end

  private
  
  def newspaper_params
    params.require(:newspaper).permit Newspaper::NEWSPAPER_PARAMS
  end

  def load_newspaper
    @newspaper = Newspaper.find_by id: params[:id]
    return if @newspaper
    flash[:danger] = t "error"
    redirect_to root_path
  end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :load_newspaper, except: %i(new create index search)

  def index; end

  def show
    @newspaper_new = Newspaper.includes(:comments)
    .take Settings.paging_table
    @comment = Comment.new
    @comments = @newspaper.comments.order_comment_by_id.take(Settings.paging_table_comment)

  end

  def search
    @newspapers = Newspaper.ransack(params[:q]).result.page(params[:page])
      .per Settings.paging_table
  end

  private

  def newspaper_params
    params.require(:newspaper).permit Newspaper::NEWSPAPER_PARAMS
  end

  def load_newspaper
    @newspaper = Newspaper.find_by id: params[:id]
    
    return if @newspaper
    flash[:danger] = t "error"
    redirect_to root_path
 end
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
  def get_category
    Category.pluck :name, :id
  end 
end

app/views/admin/newspapers/_form.html.erb
<%= form_for [:admin, @newspaper] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group col-sm-6">
    <%= f.text_field :title, autofocus: true, class: "form-control form-control-user",
      placeholder: t("tilte_new") %>
  </div>
  
  <div class="form-group col-sm-6">
    <%= f.select :category_id, get_category, {include_blank: t("category_new")}, {class: "form-control"} %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.select :status, options_for_select(Newspaper.statuses.map { |key, value| [key.humanize, key] }), {include_blank: t("news_styles")}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, accept: "image/png,image/gif,image/jpeg" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "ckeditor" %>
  </div>

  <%= button_tag t("submit"), type: "submit", class: "btn btn-primary" %>
  <%= button_tag t("reset"), type: "reset", class: "btn btn-default" %>
<% end %>

app/views/admin/newspapers/_newspaper.html.erb
<tr>
  <td><span><%= get_index_page newspaper_counter %></span></td>
  <td><%= newspaper.title %></td>
  <td>
      <%= image_tag "#{newspaper.image}" , class: "mx-auto img-fluid img-circle d-block mw", alt: "avatar" %>
  </td>
  <td><%= newspaper.created_at.strftime(t("format_time")) %></td>
  <td><%= newspaper.updated_at.strftime(t("format_time")) %></td>
  <td class="text-center">
    <%= link_to edit_admin_newspaper_path(newspaper) do %>
    <i class="fa fa-pencil fa-fw fa-update"></i>
    <% end %>   
    <%= link_to [:admin, newspaper], method: :delete, data:{ confirm: t("you_sure")} do %>
    <i class="fa fa-trash-o fa-fw fa-delete"></i>
    <% end %>    
  </td>
</tr>

app/views/admin/newspapers/edit.html.erb
<%= provide :title, t("edit_newspaper") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <hr class="invisible">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "edit_newspaper" %></h6>
  </div>
  <div class="card-body">
    <%= render "admin/newspapers/form" %>
  </div>
</div>

app/views/admin/newspapers/index.html.erb
<%= provide :title, t("list_news") %>
<%= link_to t("create_new"), new_admin_newspaper_path, class: "btn btn-primary" %>
<hr class="invisible">
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "list_news" %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr class="text-center">
            <th><%= t "stt" %></th>
            <th><%= t "title" %></th>
            <th><%= t "image" %></th>
            <th><%= t "created_time" %></th>
            <th><%= t "update_time" %></th>
            <th><%= t "action" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "newspaper", collection: @newspapers %>	
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @newspapers, theme: t("theme_paging") %>

app/views/admin/newspapers/new.html.erb
<%= provide :title, t("create_new") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <hr class="invisible">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "create_new" %></h6>
  </div>
  <div class="card-body">
    <%= render "admin/newspapers/form"%>
  </div>
</div>