config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users,
    controllers:{ omniauth_callbacks:"users/omniauth_callbacks" }

  resources :users, only: %i(show)
  namespace :admin do
    get "index"
    resources :users
    resources :categories
    resources :newspapers
    resources :leagues
    resources :seasons
    resources :players
    resources :rounds do
      resources :matches
    end
    resources :football_clubs
  end
  get "categories/new"
  mount Ckeditor::Engine => "/ckeditor"
  get "/categories", to: "home#index"
  get "/search", to:"newspapers#search"
  resources :categories
  resources :newspapers
  resources :comments
  resources :matchs
  resources :bets  
end

app/models/player.rb
class Player < ApplicationRecord
  PLAYER_PARAMS = %i(name position number country birthday football_club_id).freeze
  enum position: {gk: 1, sw: 2, cb: 3, rb: 4, lb: 5, cdm: 6, cm: 7, cam: 8, lm: 9, rm: 10, lf: 11, rf: 12, cf: 13, st: 14}
  
  belongs_to :football_club

  validates :name, presence: true
  validates :position, presence: true
  validates :number, presence: true

   delegate :name, to: :football_club, prefix:true
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < AdminController
  before_action :load_player, except: %i(new create index)

   def index
    @players = Player.page(params[:page]).per Settings.paging_table
  end

   def new
    @player = Player.new
  end

   def create
    @player = Player.new player_params

    if @player.save
      flash[:success] = t("success")
      redirect_to admin_players_path
    else
      render :new
    end
  end

   def show; end

   def edit; end

   def update
    if @player.update player_params
      flash[:success] =  t "success"
      redirect_to admin_players_path
    else
      render :edit
    end
  end

   def destroy
    if @player.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "error"
    end
    redirect_to admin_players_path
  end
  
  private

   def player_params
    params.require(:player).permit Player::PLAYER_PARAMS
  end

   def load_player
    @player = Player.find_by id: params[:id]

    return if @player
    flash[:danger] = t "error"
    redirect_to root_path
  end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
  def get_football_club
    FootballClub.pluck :name, :id
  end
end

app/views/admin/players/_form.html.erb
<%= form_for [:admin, @player] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group col-sm-6">
    <%= f.text_field :name, autofocus: true, class: "form-control form-control-user",
      placeholder: t("name") %>
  </div>

   <div class="form-group col-sm-6">
    <%= f.select :position, options_for_select(Player.positions.map { |key, value| [key.upcase, key] }), {include_blank: t("position")}, {class: "form-control"} %>
  </div>

   <div class="form-group col-sm-6">
    <%= f.text_field :number, class: "form-control form-control-user",
      placeholder: t("number") %>
  </div>

   <div class="form-group col-sm-6">
    <%= f.text_field :country, class: "form-control form-control-user",
      placeholder: t("country") %>
  </div>

   <div class="form-group col-sm-6">
    <%= f.select :football_club_id, get_football_club, {include_blank: t("football_club")}, {class: "form-control"} %>
  </div>

   <div class="form-group col-sm-6 select-time">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, class: "datepicker"  %>
  </div>

   <%= button_tag t("submit"), type: "submit", class: "btn btn-primary" %>
  <%= button_tag t("reset"), type: "reset", class: "btn btn-default" %>
<% end %> 

app/views/admin/players/_player.html.erb
<tr>
  <td><span><%= get_index_page player_counter %></span></td>
  <td><%= player.name %></td>
  <td><%= player.number %></td>
  <td><%= player.country %></td>
  <td><%= player.birthday.strftime(t("format_time")) %></td>
  <td><%= player.football_club_name %></td>
  <td class="text-center">
    <%= link_to edit_admin_player_path(player) do %>
    <i class="fa fa-pencil fa-fw fa-update"></i>
    <% end %>   
    <%= link_to [:admin, player], method: :delete, data:{ confirm: t("you_sure")} do %>
    <i class="fa fa-trash-o fa-fw fa-delete"></i>
    <% end %>    
  </td>
</tr>

app/views/admin/players/edit.html.erb
<%= provide :title, t("edit_player") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <hr class="invisible">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "edit_player" %></h6>
  </div>
  <div class="card-body">
    <%= render "admin/players/form" %>
  </div>
</div>

app/views/admin/players/index.html.erb
<%= provide :title, t("list_player") %>
<%= link_to t("create_player"), new_admin_player_url, class: "btn btn-primary" %>
<hr class="invisible">
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "list_player" %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr class="text-center">
            <th><%= t "stt" %></th>
            <th><%= t "name" %></th>
            <th><%= t "number" %></th>
            <th><%= t "country" %></th>
            <th><%= t "birthday" %></th>
            <th><%= t "football_club" %></th>
            <th><%= t "action" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "player", collection: @players %>	    
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @players, theme: t("theme_paging") %>

app/views/admin/players/new.html.erb
<%= provide :title, t("create_player") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <hr class="invisible">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "create_player" %></h6>
  </div>
  <div class="card-body">
    <%= render "admin/players/form"%>
  </div>
</div>