config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users,
    controllers:{ omniauth_callbacks:"users/omniauth_callbacks" }

  resources :users, only: %i(show)
  namespace :admin do
    get "index"
    resources :users
    resources :categories
    resources :newspapers
    resources :leagues
    resources :seasons
    resources :players
    resources :rounds do
      resources :matches
    end
    resources :football_clubs
  end
  get "categories/new"
  mount Ckeditor::Engine => "/ckeditor"
  get "/categories", to: "home#index"
  get "/search", to:"newspapers#search"
  resources :categories
  resources :newspapers
  resources :comments
  resources :matchs
  resources :bets  
end

app/models/match.rb
class Match < ApplicationRecord
  after_update :resule_match_for_bet, if: -> {self.fought?}
  MATCH_PARAMS = %i(home_team_id guest_team_id start_time finish_time goals_home_team goals_guest_team round_id status).freeze
  enum status: {unfought: 0, fighting: 1, fought: 2}

  belongs_to :round
  belongs_to :home_team, class_name: FootballClub.name
  belongs_to :guest_team, class_name: FootballClub.name
  has_many :bets, dependent: :destroy

  delegate :round_number, to: :round, prefix: true

  def resule_match_for_bet
    result = goals_home_team - goals_guest_team
    self.bets.each do |bet|
      if (bet.win? && result > 0) || (bet.lost? && result < 0) || (bet.draw? && result == 0)
        bet.exactly!
      else
        bet.incorrect!
      end
    end
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < AdminController
  before_action :load_round_by_id
  before_action :load_match, except: %i(new create index)
  def index
    @matches = @round.matches.page(params[:page]).per Settings.paging_table
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new match_params
    if @match.save

      flash[:success] = t("success")
      redirect_to admin_round_matches_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    # update_rank_update
    if @match.update match_params
      flash[:success] =  t "success"
      redirect_to admin_round_matches_path
    else
      render :edit
    end
  end

  def destroy
    if @match.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "error"
    end
    redirect_to admin_round_matches_path
  end

  private

  def match_params
    params.require(:match).permit Match::MATCH_PARAMS
  end

  def load_match
    @match = Match.find_by id: params[:id]
    return if @match
    flash[:danger] = t "error"
    redirect_to root_path
  end

  def load_round_by_id
    @round = Round.find_by id: params[:round_id]
  end

  # def update_rank_update
  #   rank_home = Ranking.find_by season_id: @match.round.season.id, football_club_id: @match.home_team.id
  #   rank_guest = Ranking.find_by season_id: @match.round.season.id, football_club_id: @match.guest_team.id
  #   goal_of_old_match_home = @match.goals_home_team.to_i
  #   goal_of_new_match_home = params[:match][:goals_home_team].to_i
  #   goal_of_old_match_guest = @match.goals_guest_team.to_i
  #   goal_of_new_match_guest = params[:match][:goals_guest_team].to_i
  #   rank_home.update_attributes goals_number: rank_home.goals_number - goal_of_old_match_home + goal_of_new_match_home,
  #     goals_lost_number: rank_home.goals_lost_number - goal_of_old_match_guest + goal_of_new_match_guest
  #   rank_guest.update_attributes goals_number: rank_guest.goals_number - goal_of_old_match_guest + goal_of_new_match_guest,
  #     goals_lost_number: rank_guest.goals_lost_number - goal_of_old_match_home + goal_of_new_match_home
    
  # end
end

app/controllers/admin/matchs_controller.rb
class Admin::MatchsController < AdminController
  before_action :load_match, except: %i(new create index)

  def index
    @matchs = Match.page(params[:page]).per Settings.paging_table
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new match_params
    
    if @match.save
      flash[:success] = t("success")
      redirect_to admin_matchs_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @match.update match_params
      flash[:success] =  t "success"
      redirect_to admin_matchs_path
    else
      render :edit
    end
  end

  def destroy
    if @match.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "error"
    end
    redirect_to admin_matchs_path
  end

  private
  
  def match_params
    params.require(:match).permit Match::MATCH_PARAMS
  end

  def load_match
    @match = Match.find_by id: params[:id]
    return if @match
    flash[:danger] = t "error"
    redirect_to root_path
  end
end

app/controllers/matchs_controller.rb
class MatchsController < ApplicationController
  before_action :load_match, except: %i(new create index)
  before_action :load_leagues
  before_action :load_league

  def index        
    if @league
      @season = Season.includes(:rounds).find_by id: params[:season]
      if @season
        @rounds = @season.rounds
        @round = Round.find_by id: params[:round]
        @matches = @round.matches if @round
      end
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def load_leagues
    @leagues = League.all
  end

  def load_league
    @league = League.includes(:seasons).find_by id: params[:league]
  end

  def show
    @bet = Bet.new
  end

  def load_match
    @match = Match.find_by id: params[:id]
    return if @match
    flash[:danger] = t "error"
    redirect_to root_path
  end
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
	def get_football_clubs round
    Season.find_by(id: round.season.id).football_clubs.collect{ |m| [m.name, m.id] }
  end

  def get_league
    Round.pluck :name, :id
  end 
end

app/helpers/admin/matchs_helper.rb
module Admin::MatchsHelper
end

app/helpers/matchs_helper.rb
module MatchsHelper
end

app/views/admin/matches/_form.html.erb
<%= form_for [:admin,@round,@match] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group col-sm-6">
    <%= f.select :home_team_id, get_football_clubs(@round) , {include_blank: t("football_club")}, {class: "form-control"} %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.select :guest_team_id,get_football_clubs(@round), {include_blank: t("football_club")}, {class: "form-control"} %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time, class: "datepicker"  %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.label :finish_time %><br>
    <%= f.datetime_select :finish_time %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.text_field :goals_home_team, autocomplete: "goalshometeam", value: "0",
      class: "form-control form-control-user", placeholder: t("goals_home_team") %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.text_field :goals_guest_team, autocomplete: "goals_guest_team", value: "0",
      class: "form-control form-control-user", placeholder: t("goals_guest_team") %>
  </div>

  <%= f.hidden_field :round_id, value: @round.id, class: "form-control mb-1" %>

  <div class="form-group col-sm-6">
    <%= f.select :status, options_for_select(Match.statuses.map { |key, value| [key.humanize, key] }), {include_blank: t("status")}, {class: "form-control"} %>
  </div>

  <%= button_tag t("submit"), type: "submit", class: "btn btn-primary" %>
  <%= button_tag t("reset"), type: "reset", class: "btn btn-default" %>

<% end %>

app/views/admin/matches/_match.html.erb
<tr>
  <td><span><%= get_index_page match_counter %></span></td>
  <td><%= match.home_team.name %></td>
  <td><%= match.guest_team.name %></td>
  <td><%= match.start_time.strftime(t("format_time_match")) %></td>
  <td><%= match.goals_home_team %></td>
  <td><%= match.goals_guest_team %></td>
  <td><%= match.round_round_number %></td>
  <td><%= match.status %></td>  
  <td class="text-center">
    <%= link_to edit_admin_round_match_path(id: match.id) do %>
    <i class="fa fa-pencil fa-fw fa-update"></i>
    <% end %>   
    <%= link_to [:admin,@round,@match], method: :delete, data:{ confirm: t("you_sure")} do %>
    <i class="fa fa-trash-o fa-fw fa-delete"></i>
    <% end %>    
  </td>
</tr>

app/views/admin/matches/edit.html.erb
<%= provide :title, t("edit_match") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <hr class="invisible">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "edit_match" %></h6>
  </div>
  <div class="card-body">
    <%= render "admin/matches/form"%>
  </div>
</div>

app/views/admin/matches/index.html.erb
<%= provide :title, t("list_match") %>
<%= link_to t("create_match"), new_admin_round_match_url, class: "btn btn-primary" %>
<hr class="invisible">
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "list_match" %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr class="text-center">
            <th><%= t "stt" %></th>
            <th><%= t "home_team" %></th>
            <th><%= t "guest_team_id" %></th>
            <th><%= t "start_time" %></th>
            <th><%= t "goals_home_team" %></th>
            <th><%= t "goals_guest_team" %></th>
            <th><%= t "round" %></th>
            <th><%= t "status" %></th>
            <th><%= t "action" %></th>
          </tr>
        </thead>
        <tbody>
					<%= render partial: "match", collection: @matches %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/matches/new.html.erb
<%= provide :title, t("create_match") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <hr class="invisible">
    <h6 class="m-0 font-weight-bold text-primary"><%= t "create_match" %></h6>
  </div>
  <div class="card-body">
    <%= render "admin/matches/form"%>
  </div>
</div>