config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users,
    controllers:{ omniauth_callbacks:"users/omniauth_callbacks" }

  resources :users, only: %i(show)
  namespace :admin do
    get "index"
    resources :users
    resources :categories
    resources :newspapers
    resources :leagues
    resources :seasons
    resources :players
    resources :rounds do
      resources :matches
    end
    resources :football_clubs
  end
  get "categories/new"
  mount Ckeditor::Engine => "/ckeditor"
  get "/categories", to: "home#index"
  get "/search", to:"newspapers#search"
  resources :categories
  resources :newspapers
  resources :comments
  resources :matchs
  resources :bets  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  after_create_commit :set_default_result_bet
  BET_PARAMS = %i(user_id match_id result status).freeze
  enum status: {incorrect: 0, exactly: 1, waiting: 2}
  enum result: {lost: 0, draw: 1, win: 2}

  belongs_to :user
  belongs_to :match

  validates :result, presence: true

  scope :by_user_and_bet, ->(user_id, match_id){where user_id: user_id, match_id: match_id}

  def set_default_result_bet
    self.update_attributes status: :waiting
  end
end

app/models/category.rb
class Category < ApplicationRecord
  CATEGORY_PARAMS = %i(name status).freeze
  enum status: {not_show: 0, show: 1}

  has_many :newspapers, dependent: :destroy

  scope :by_status_show, -> {where status: :show}
end

app/models/comment.rb
class Comment < ApplicationRecord
  COMMENT_PARAMS = %i(content user_id newspaper_id).freeze
  belongs_to :user
  belongs_to :newspaper

  validates :content, presence: true

  scope :order_comment_by_id, -> {order id: :desc}
end

app/models/football_club.rb
class FootballClub < ApplicationRecord
  FOOTBALL_CLUB_PARAMS = %i(name description member stadium logo).freeze

  has_many :players, dependent: :destroy
  has_many :rankings, dependent: :destroy
  has_many :seasons, through: :rankings
  has_many :home_team, class_name: Match.name, foreign_key: "home_team",
    dependent: :destroy
  has_many :guest_team, class_name: Match.name, foreign_key: "guest_team",
    dependent: :destroy

  mount_uploader :logo, ImageUploader

  validates :name, presence: true, uniqueness: true
  validates :stadium, presence: true
end

app/models/league.rb
class League < ApplicationRecord
  LEAGUE_PARAMS = %i(name country).freeze
  
  has_many :seasons, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/models/match.rb
class Match < ApplicationRecord
  after_update :resule_match_for_bet, if: -> {self.fought?}
  MATCH_PARAMS = %i(home_team_id guest_team_id start_time finish_time goals_home_team goals_guest_team round_id status).freeze
  enum status: {unfought: 0, fighting: 1, fought: 2}

  belongs_to :round
  belongs_to :home_team, class_name: FootballClub.name
  belongs_to :guest_team, class_name: FootballClub.name
  has_many :bets, dependent: :destroy

  delegate :round_number, to: :round, prefix: true

  def resule_match_for_bet
    result = goals_home_team - goals_guest_team
    self.bets.each do |bet|
      if (bet.win? && result > 0) || (bet.lost? && result < 0) || (bet.draw? && result == 0)
        bet.exactly!
      else
        bet.incorrect!
      end
    end
  end
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
  NEWSPAPER_PARAMS = %i(title description image status category_id).freeze
  enum status: {normal: 0, hot: 1, most_new: 2}

  has_one_attached :image
  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy
  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true

  delegate :name, to: :category, prefix: true

  scope :ordered_by_newspaper_id, -> {order(id: :desc)}
  scope :by_status_hot, -> {where status: 1}
  scope :by_status_normal, -> {where status: 0}
  scope :get_new_by_category_ids, ->(category_ids){where category_id: category_ids}
  scope :limit_show_newspapers, -> {order(id: :asc).limit 4}
end

app/models/player.rb
class Player < ApplicationRecord
  PLAYER_PARAMS = %i(name position number country birthday football_club_id).freeze
  enum position: {gk: 1, sw: 2, cb: 3, rb: 4, lb: 5, cdm: 6, cm: 7, cam: 8, lm: 9, rm: 10, lf: 11, rf: 12, cf: 13, st: 14}
  
  belongs_to :football_club

  validates :name, presence: true
  validates :position, presence: true
  validates :number, presence: true

   delegate :name, to: :football_club, prefix:true
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :football_club
  belongs_to :season
end

app/models/round.rb
class Round < ApplicationRecord
  ROUND_PARAMS = %i(round_number season_id).freeze

  belongs_to :season
  has_many :matches, dependent: :destroy

  delegate :start_time, to: :season, prefix: true
  delegate :finish_time, to: :season, prefix: true
end

app/models/season.rb
class Season < ApplicationRecord
  SEASON_PARAMS = %i(start_time finish_time league_id).freeze
  
  belongs_to :league
  has_many :rounds, dependent: :destroy
  has_many :rankings, dependent: :destroy
  has_many :football_clubs, through: :rankings, dependent: :destroy

  delegate :name, to: :league, prefix: true

  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  USER_PARAMS = %i(name email password avatar).freeze

  has_one_attached :avatar

  has_many :comments, dependent: :destroy
  has_many :bets, dependent: :destroy
  mount_uploader :avatar, ImageUploader

  def new_with_session params, session
    tap do |user|
      if data = session["devise.facebook_data"] &&
        session[:devise.facebook_data][:extra][:raw_info]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  class << self
    def from_omniauth auth      
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.name = auth.info.name
      end
    end
  end

  def current_user? user
    self == user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :load_bet, except: %i(new create index)
  
  def index; end

  def new
    @bet = Bet.new
  end

  def create
    @bet = Bet.new bet_params

    if @bet.save
      flash[:success] = t "success"
      redirect_to request.referrer
    end
  end

  private
  
  def bet_params
    params.require(:bet).permit Bet::BET_PARAMS
  end

  def load_bet
    @bet = Bet.find_by id: params[:id]

    return if @bet
    flash[:danger] = t "error"
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  def index
    @newspaper_hots = Newspaper.ordered_by_newspaper_id.by_status_hot.take Settings.show_newspaper_home
    @newspaper_normals = Newspaper.by_status_normal.take Settings.show_newspaper_home
    @categories_show = Category.by_status_show.take Settings.show_newspaper_home
    @newspapers_show = get_new_of_category @categories_show.map &:id
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_index_page page = :page, key
    params[page].to_i * Settings.end_stt + key + Settings.start_stt
  end

  def get_index key
    key + Settings.start_stt
  end

  def count_user_id_math_id match_id
    Bet.by_user_and_bet(current_user.id, match_id).count
  end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_new_of_category category_ids
    Newspaper.get_new_by_category_ids category_ids
  end

  def get_newspaper_home_page category
    category.newspapers.limit_show_newspapers
  end
end

app/helpers/matchs_helper.rb
module MatchsHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
  def get_category
    Category.pluck :name, :id
  end 
end

app/views/home/index.html.erb
<div class="popular-news-area section-padding-80-50">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-8">
        <div class="section-heading">
          <h6><%= t "new_News"%></h6>
        </div>
        <div class="row">
          <% @newspaper_hots.each do |newspaper_hot| %>
            <div class="col-12 col-md-6">
              <div class="single-blog-post style-3">
                <div class="post-thumb">
                  <%= link_to newspaper_path(newspaper_hot) do %>
                     <%= image_tag "#{newspaper_hot.image}" , alt: "avatar" %>
                  <% end %>  
                </div>
                <div class="post-data">
                  <%= link_to newspaper_path(newspaper_hot) do %>
                     <h6><%= newspaper_hot.title %></h6>
                  <% end %>
                  <p><%= raw( newspaper_hot.description.slice(Settings.start_char..Settings.end_char)) %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-lg-4">
        <div class="section-heading">
          <h6><%= t "related_news"%></h6>
        </div>
        <% @newspaper_normals.each do |newspaper_normal| %>
          <div class="single-blog-post small-featured-post d-flex">
            <div class="post-thumb news_normal">
              <%= link_to newspaper_path(newspaper_normal) do %>
                <%= image_tag "#{newspaper_normal.image}" , alt: "avatar" %>
              <% end %>  
            </div>
            <div class="post-data">
              <%= link_to newspaper_normal.category_name, category_path(newspaper_normal.category_id), class:"post-catagory" %>
              <div class="post-meta">
                <%= link_to newspaper_path(newspaper_normal), class:"post-title newlq" do %>
                  <h6><%= newspaper_normal.title %></h6>
                <% end %>  
                <p class="post-date"><%= newspaper_normal.created_at %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="editors-pick-post-area section-padding-80-50">
  <div class="container">
    <div class="row">
      <% @categories_show.each do |category_show| %>
        <div class="col-12 col-md-12 col-lg-12">
          <div class="section-heading">
            <h6><%= category_show.name %></h6>
          </div>
          <div class="row">
            <% get_newspaper_home_page(category_show).each do |newspaper_show| %>
            <div class="col-12 col-lg-3">
              <div class="single-blog-post news-category">
                <div class="post-thumb-category">
                  <%= link_to newspaper_path(newspaper_show) do %>
                    <%= image_tag "#{newspaper_show.image}" , alt: "avatar" %>
                  <% end %>
                </div>
                <div class="post-data">
                    <%= link_to newspaper_path(newspaper_show) do %>
                      <h6><%= newspaper_show.title %></h6>
                    <% end %>
                    <div class="post-meta">
                      <div class="post-date"><%= link_to newspaper_show.created_at.strftime(t("format_time")) , newspaper_path(newspaper_show) %></div>
                    </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>